### ISSUE TITLE
jitsi meet integration in Ionic App

### ISSUE THREAD

**Issue by jyothimarkal** [ionic-team/appflow-build#117]
How to use jitsi in Ionic App ? please give me step-by-step instructions i try to follow the instruction provided in the documentation but it's not clear me.

**Comment by smzelek** [comment]
@jyothimarkal Consider asking in the Ionic forums: https://forum.ionicframework.com/. This is not the proper place for that question.

**Comment by jyothimarkal** [comment]
Okay Thank u for response
