### ISSUE TITLE
How to trigger the release for an arbitrary commit?

### ISSUE THREAD

**Issue by lauromueller** [ionic-team/appflow-build#58]
Hello 👋 

We currently have Appflow integrated in our project, and the GitHub action would be great to automate the build process and speed up our release workflow. However, there doesn't seem to be an option to trigger the build commands for a specific commit different from the GITHUB_SHA environment variable.

Is it possible to trigger the build workflow for an arbitrary commit?

Thanks!

**Comment by matthewkremer** [comment]
Hey @lauromueller, correct, right now this is not possible. We're currently working on some modifications to our CLI integration, and will investigate how that might affect this request. Thanks!

**Comment by lauromueller** [comment]
Understood, thank you for the quick reply!
